# Generated by Django 3.2.3 on 2021-06-06 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bikes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bikes',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='bike',
        ),
        migrations.DeleteModel(
            name='MotorBike',
        ),
    ]
