# Generated by Django 3.2.3 on 2021-06-08 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('renting_bike', '0002_rename_destination_bikes'),
        ('app', '0004_rent_total_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='bike',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='renting_bike.bikes'),
            preserve_default='True',
        ),
    ]
