# Generated by Django 3.2.3 on 2021-06-16 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210616_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='password2',
        ),
    ]
