# Generated by Django 3.2.3 on 2021-06-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting_bike', '0002_rename_destination_bikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
